### ISSUE TITLE
The plugin Search+ in Roam Depot does not match your theme a bit, mainly because the left side is not aligned. Can you optimize it?

### ISSUE THREAD

**Issue by zacharylabs** [abhayprasanna/abhayprasanna.github.io#19]
The plugin Search+ in Roam Depot is very useful, but it does not match your theme a bit, mainly because the left side is not aligned. Can you optimize it? Thank you!

![](https://cdn.jsdelivr.net/gh/ZacharyLauGitHub/images/2023/CleanShot%202023-02-01%20at%2011.52.11@2x.png)

**Comment by abhayprasanna** [comment]
@dive2Pro I would recommend using the following syntax to create the div for this button so that it follows theme styling of the other buttons in the left sidebar.

https://github.com/abhayprasanna/roam-random-block/blob/35b329d0dbdd7994642d04dfa721b7a6469a52bd/extension.js#L1-L17

**Comment by abhayprasanna** [comment]
@ZacharyLauGitHub I've suggested a change to the extension creator.

**Comment by dive2Pro** [comment]
@ZacharyLauGitHub  You can use this snippet to adjust the style of the Search+ button

```css
.roam-sidebar-container .log-button {
  transform: scale(1);
}

.roam-sidebar-container .log-button .bp3-button-text {
    color: white !important;
}
```

![image](https://user-images.githubusercontent.com/23192045/216224735-162421c4-bf3e-4ea5-af47-be9e83128698.png)

@abhayprasanna thx for suggestion. The code didn't fit my needs and I added a tooltip for the "Search+" button.
